name: Go
on:
  push:
    # branches:
    #   - main
    tags:
      - v1.*.*
  pull_request:
    branches:
      - main

jobs:
  goreleaser:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        if: matrix.platform == 'ubuntu-latest'
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f .goreleaser.linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      -
        if: matrix.platform == 'macos-latest'
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f .goreleaser.mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        if: matrix.platform == 'windows-latest'
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f .goreleaser.win.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        if: matrix.platform == 'ubuntu-latest'
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: disass_macos
          path: dist/*
      -
        if: matrix.platform == 'macos-latest'
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: disass_linux
          path: dist/*
      -
        if: matrix.platform == 'windows-latest'
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: disass.exe
          path: dist/*